name: Alert parent repository on push
on: push

jobs:
  wait-and-dispatch:
    name: Wait image building and trigger other repo
    runs-on: ubuntu-latest
    steps:
      - name: Trigger repo
        uses: PaulLesur/wait-docker-image-github-action@v1.0
        with:
          image: nginx
          tag: latest
          timeout: 20
          fail-on-timeout: true
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
# Токен другой репы
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: svc-broadcaster-k8s-test
          owner: hdclone
          event_type: sample_push

