name: "Triggering other repo by tag"
on:
  push:
    tags:        
      - '*'

jobs:
  wait-and-dispatch:
    name: Wait image building and trigger other repo
    runs-on: ubuntu-latest
    steps:
      - name: Check
        run: |
          echo "${{ GITHUB_REF_NAME }}"
      - name: Waiting docker image build
        uses: PaulLesur/wait-docker-image-github-action@v1.0
        with:
          image: "symbiosisfinance/svc-broadcaster"
          tag: "0.0.8-tx"
          timeout: 600
          fail-on-timeout: true
          user: "${{ secrets.DOCKERHUB_LOGIN }}"
          password: "${{ secrets.DOCKERHUB_PASSWORD }}"
      - name: Emit repository_dispatch
        uses: mvasigh/dispatch-action@main
        with:
# Токен другой репы
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repo: svc-broadcaster-k8s-test
          owner: hdclone
          event_type: sample_push
          message: |
            {
              "eslinizhe": "${{ github.sha }}",
              "esliwishe": "pidor"
            }

